name: Build

on:
    push:
        branches: [master]

    # Run tests for any PRs.
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js to build
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm i
            - run: npm run lint:js
            - run: npm test
            - run: npm run build
              env:
                  CI: true
